### ISSUE TITLE
File 'ions.tpr' does not exist or is not accessible.

### ISSUE THREAD

**Issue by em-oz** [tubiana/protocolGromacs#4]
Hi, thank you for this script. I am having issues with ions.tpr file and it looks like the command that generates it fails.

```
Error in user input:
Invalid command-line options
  In command-line option -s
    File 'ions.tpr' does not exist or is not accessible.
    The file could not be opened.
      Reason: No such file or directory
      (call to fopen() returned error code 2)
```

If I run this command manually;

`gmx grompp -f mdp/ions.mdp -c complex_solv.gro -p topol.top -o ions.tpr `

It also gives me this error:

```
Program:     gmx grompp, version 2021.4-Ubuntu-2021.4-2
Source file: src/gromacs/gmxpreprocess/grompp.cpp (line 614)

Fatal error:
No molecules were defined in the system
```

Thanks again

**Comment by Marwa-Abdelkader** [comment]
I suggest making sure the ions.mdp file exists in the same working directory not in the mdp folder, it should work if your protein structure is correctly prepared

**Comment by tubiana** [comment]
Hi, 

Thank you for answering @Marwa-Abdelkader , I completely forgot to answer, sorry about that. 
The problem cames from grompp, check your input structure if everything seems "fine"...
