### ISSUE TITLE
ERROR: ACPYPE FAILED

### ISSUE THREAD

**Issue by EsToHi** [tubiana/protocolGromacs#7]
Hello,

Thank you for this amazing script.
I got an error while converting molecule using ACPYPE to prepare topology:
(gmx) hicham@DESKTOP-E3HV849:~/gmxNew/protocolGromacs$ ./runGromacs.sh
0 molecules converted
============================================================================
| ACPYPE: AnteChamber PYthon Parser interfacE v. 2023.10.27 (c) 2023 AWSdS |
============================================================================
ERROR: ACPYPE FAILED:
Traceback (most recent call last):
  File "/home/hicham/miniconda3/envs/gmx/lib/python3.8/site-packages/acpype/cli.py", line 106, in init_main
    molecule = ACTopol(
  File "/home/hicham/miniconda3/envs/gmx/lib/python3.8/site-packages/acpype/topol.py", line 3325, in __init__
    self.setResNameCheckCoords()
  File "/home/hicham/miniconda3/envs/gmx/lib/python3.8/site-packages/acpype/topol.py", line 567, in setResNameCheckCoords

**Comment by tubiana** [comment]
Hi! 

The problem is comming from the acpype package. You should try to run it outside my script (with `acpype -i mol.mol2`) to check if you have more details on the error, it seems the message is not complete...

**Comment by EsToHi** [comment]
What should format of the ligand input be ? Cuz I used .pdb as ligand input format.. is it correct ?

**Comment by EsToHi** [comment]
**The error is too long ot put it all here, but here's more details:**
(gmx) hicham@DESKTOP-E3HV849:~/gmxNew/protocolGromacs$ ./runGromacs.sh
mkdir: cannot create directory ‘param’: File exists
0 molecules converted
============================================================================
| ACPYPE: AnteChamber PYthon Parser interfacE v. 2023.10.27 (c) 2023 AWSdS |
============================================================================
ERROR: ACPYPE FAILED:
Traceback (most recent call last):
  File "/home/hicham/miniconda3/envs/gmx/lib/python3.8/site-packages/acpype/cli.py", line 106, in init_main
    molecule = ACTopol(
  File "/home/hicham/miniconda3/envs/gmx/lib/python3.8/site-packages/acpype/topol.py", line 3325, in __init__
    self.setResNameCheckCoords()
  File "/home/hicham/miniconda3/envs/gmx/lib/python3.8/site-packages/acpype/topol.py", line 567, in setResNameCheckCoords
    resname = next(iter(residues)).strip()
StopIteration
Total time of execution: less than a second
Log tmp location: /tmp/tmpgnx1ue9u
mkdir: cannot create directory ‘ligand’: File exists
mv: cannot move 'ligand' to a subdirectory of itself, 'ligand/ligand'
mkdir: cannot create directory ‘receptor’: File exists
                     :-) GROMACS - gmx pdb2gmx, 2023.3 (-:

Executable:   /usr/local/gromacs/bin/gmx
Data prefix:  /usr/local/gromacs
Working dir:  /home/hicham/gmxNew/protocolGromacs/param/receptor
Command line:
  gmx pdb2gmx -f receptor.pdb -o receptor_GMX.pdb -water tip3p -ignh -ff amber99sb-ildn

Using the Amber99sb-ildn force field in directory amber99sb-ildn.ff

going to rename amber99sb-ildn.ff/aminoacids.r2b
Opening force field file /usr/local/gromacs/share/gromacs/top/amber99sb-ildn.ff/aminoacids.r2b
.....
**I convert ligand.pdb to ligand.mol2
Regarding the command u ask for :**
(gmx) hicham@DESKTOP-E3HV849:~/gmxNew/protocolGromacs$ acpype -i ATM.mol2
============================================================================
| ACPYPE: AnteChamber PYthon Parser interfacE v. 2023.10.27 (c) 2023 AWSdS |
============================================================================
WARNING: no charge value given, trying to guess one...
==> ... charge set to 1
==> Executing Antechamber...
ERROR: ++++++++++start_quote+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ERROR:
Welcome to antechamber 19.0: molecular input file processor.

Info: Finished reading file (ATM.mol2); atoms read (68), bonds read (76).
Running: /home/hicham/miniconda3/envs/gmx/bin/bondtype -j full -i ANTECHAMBER_BOND_TYPE.AC0 -o ANTECHAMBER_BOND_TYPE.AC -f ac
Warning: The assigned bond types may be wrong, please :
(1) double check the structure (the connectivity) and/or
(2) adjust atom valence penalty parameters in APS.DAT, and/or
(3) increase PSCUTOFF in define.h and recompile bondtype.c
 (be cautious, using a large value of PSCUTOFF (>100) will
 significantly increase the computation time).

Running: /home/hicham/miniconda3/envs/gmx/bin/atomtype -i ANTECHAMBER_AC.AC0 -o ANTECHAMBER_AC.AC -p gaff2
Info: Total number of electrons: 445; net charge: 1
Info: The number of electrons is odd (445).
 Please check the total charge (-nc flag) and spin multiplicity (-m flag).

Running: /home/hicham/miniconda3/envs/gmx/bin/sqm -O -i sqm.in -o sqm.out
/home/hicham/miniconda3/envs/gmx/bin/to_be_dispatched/antechamber: Fatal Error!
Cannot properly run "/home/hicham/miniconda3/envs/gmx/bin/sqm -O -i sqm.in -o sqm.out".

ERROR: ++++++++++end_quote+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ERROR: Antechamber failed
ERROR: ++++++++++start_quote+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ERROR: Cannot open file (ATM_bcc_gaff2.mol2) with mode (r).
No such file or directory
ERROR: ++++++++++end_quote+++++++++++++++++++++++++++++++++++++++++++++++++++++++++++++
ERROR: Parmchk failed
ERROR: Tleap failed
==> Removing temporary files...
ERROR: ACPYPE FAILED: [Errno 2] No such file or directory: 'ATM_AC.prmtop'
Traceback (most recent call last):
  File "/home/hicham/miniconda3/envs/gmx/lib/python3.8/site-packages/acpype/cli.py", line 138, in init_main
    molecule.createMolTopol()
  File "/home/hicham/miniconda3/envs/gmx/lib/python3.8/site-packages/acpype/topol.py", line 1115, in createMolTopol
    self.topFileData = open(self.acTopFileName).readlines()
FileNotFoundError: [Errno 2] No such file or directory: 'ATM_AC.prmtop'
Total time of execution: less than a second

**Comment by tubiana** [comment]
The error seems to came from ACPYPE here, surely a problem with your ligand. 
You had the following warnings that I think you should look more into it 
```
Warning: The assigned bond types may be wrong, please :
(1) double check the structure (the connectivity) and/or
(2) adjust atom valence penalty parameters in APS.DAT, and/or
(3) increase PSCUTOFF in define.h and recompile bondtype.c
(be cautious, using a large value of PSCUTOFF (>100) will
significantly increase the computation time).
```

If you cannot fix your ligand, I suggest you open an issue into https://github.com/alanwilter/acpype.

Best regards,
Thibault.
